import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providersarea from "./Providers";
import { Toaster } from "@/components/ui/sonner"
import Header from "@/components/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Chatt site By Abdullah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
<Providersarea> 
<Header />
        {children}
        <Toaster />
</Providersarea>

        </body>
    </html>
  );
}
